name: "✨ Feature Request"
description: "새로운 기능을 제안할 때 사용하세요"
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: textarea
    id: background
    attributes:
      label: 제안 배경
      description: 어떤 문제를 해결하기 위해 이 기능이 필요한지 설명해주세요.
      placeholder: 현재 어떤 불편함이 있나요?
  - type: textarea
    id: proposal
    attributes:
      label: 제안 내용
      description: 구현하고자 하는 기능을 구체적으로 설명해주세요.
      placeholder: 사용자가 ~~ 할 수 있도록 버튼을 추가한다.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: 완료 기준 (Acceptance Criteria)
      description: 기능이 완료되었다고 판단할 수 있는 테스트 가능한 기준을 써주세요.
      placeholder: |
        - 사용자는 저장된 페이지에서 태그 자동완성을 볼 수 있다
        - 3가지 시나리오에서 E2E 테스트 통과
  - type: textarea
    id: alternatives
    attributes:
      label: 대안
      description: 고려한 다른 해결책이 있나요?
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      options: ["P0-가장 높음", "P1-높음", "P2-보통", "P3-낮음"]
      default: 2
